# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ratala321/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "itchio"
name = "itch.io"
url = "https://ratala321.itch.io/"

[social.params]
icon = "brand-itchio"

[[social]]
identifier = "rss"
name = "rss"
url = "https://ratala321.github.io/index.xml"

[social.params]
icon = "rss"
